apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
  labels:
    env: demo
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: development
        type: frontend
    spec:
      containers:
        - name: nginx-containers
          image: nginx
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 3