#Pod Definition with Resource Requests and Limits

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: development
    type: frontend
spec:
  containers:
  - name: nginx-containers
    image: nginx1234
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"